/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewSlideshowRouteImport } from './routes/preview/slideshow'
import { Route as PreviewScrollRouteImport } from './routes/preview/scroll'
import { Route as PreviewMinimalRouteImport } from './routes/preview/minimal'
import { Route as PreviewDelftRouteImport } from './routes/preview/delft'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSlideshowRoute = PreviewSlideshowRouteImport.update({
  id: '/preview/slideshow',
  path: '/preview/slideshow',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewScrollRoute = PreviewScrollRouteImport.update({
  id: '/preview/scroll',
  path: '/preview/scroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewMinimalRoute = PreviewMinimalRouteImport.update({
  id: '/preview/minimal',
  path: '/preview/minimal',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDelftRoute = PreviewDelftRouteImport.update({
  id: '/preview/delft',
  path: '/preview/delft',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview/delft': typeof PreviewDelftRoute
  '/preview/minimal': typeof PreviewMinimalRoute
  '/preview/scroll': typeof PreviewScrollRoute
  '/preview/slideshow': typeof PreviewSlideshowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview/delft': typeof PreviewDelftRoute
  '/preview/minimal': typeof PreviewMinimalRoute
  '/preview/scroll': typeof PreviewScrollRoute
  '/preview/slideshow': typeof PreviewSlideshowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview/delft': typeof PreviewDelftRoute
  '/preview/minimal': typeof PreviewMinimalRoute
  '/preview/scroll': typeof PreviewScrollRoute
  '/preview/slideshow': typeof PreviewSlideshowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview/delft'
    | '/preview/minimal'
    | '/preview/scroll'
    | '/preview/slideshow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview/delft'
    | '/preview/minimal'
    | '/preview/scroll'
    | '/preview/slideshow'
  id:
    | '__root__'
    | '/'
    | '/preview/delft'
    | '/preview/minimal'
    | '/preview/scroll'
    | '/preview/slideshow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewDelftRoute: typeof PreviewDelftRoute
  PreviewMinimalRoute: typeof PreviewMinimalRoute
  PreviewScrollRoute: typeof PreviewScrollRoute
  PreviewSlideshowRoute: typeof PreviewSlideshowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/slideshow': {
      id: '/preview/slideshow'
      path: '/preview/slideshow'
      fullPath: '/preview/slideshow'
      preLoaderRoute: typeof PreviewSlideshowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/scroll': {
      id: '/preview/scroll'
      path: '/preview/scroll'
      fullPath: '/preview/scroll'
      preLoaderRoute: typeof PreviewScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/minimal': {
      id: '/preview/minimal'
      path: '/preview/minimal'
      fullPath: '/preview/minimal'
      preLoaderRoute: typeof PreviewMinimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/delft': {
      id: '/preview/delft'
      path: '/preview/delft'
      fullPath: '/preview/delft'
      preLoaderRoute: typeof PreviewDelftRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewDelftRoute: PreviewDelftRoute,
  PreviewMinimalRoute: PreviewMinimalRoute,
  PreviewScrollRoute: PreviewScrollRoute,
  PreviewSlideshowRoute: PreviewSlideshowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
